### ISSUE TITLE
Update .npmignore

### ISSUE THREAD

**Issue by NathanaelA** [bthurlow/nativescript-maskedinput#1]
Cool plugin I just saw it in the new category on the nsrocks site.  Going to have to play with it...

Your .npmignore file should be set to ignore the .ts files and your .json files.
Only the js files need to be distributed with your plugin...   I can send you a pull request if you really want, but it seems simpler for you to just add those to things to your .npmignore and commit it :grinning:

**Comment by bthurlow** [comment]
Thanks.  I'll get that change made.
