### ISSUE TITLE
Databinding

### ISSUE THREAD

**Issue by dpdragnev** [bthurlow/nativescript-maskedinput#3]
Hello,

Do we still bind the input using the text property?  I am using:

`<mi:MaskedInput mask="(999) 999 9999" placeholder="_" text="{{ customer.homephone }}" color="#a8b4b9" />`

but the data is never displayed.

Am I missing something?

Thanks.

**Comment by bthurlow** [comment]
Android Resolved.
Reviewing iOS.

**Comment by dpdragnev** [comment]
Awesome.  Thanks Brian. :)

**Comment by bthurlow** [comment]
Prepping to push NPM.

**Comment by bthurlow** [comment]
Published.
